Jdbc
lucasz-student/Laba_MySQL pull request #1
Opened 2023-06-09 03:57 UTC by lucasz-student

- Model Classes
 - DAO Classes
 - Basic Service Classes

2023-06-09 12:10 UTC, jisha-2023 reviewed
I think the Model Package and DAO package should be on the same level. You can create another package called Service to keep all your service classes.

2023-06-09 12:32 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/Model/Gym.java
> +
You can remove this blank line.

2023-06-09 12:36 UTC, jishaGithub reviewed
I think instead of creating new JDBC connection for each request you can use connection pool to reuse jdbc connections.

2023-06-09 13:44 UTC, jisha-2023 reviewed
Good work!

2023-06-09 13:46 UTC, jishaGithub reviewed
Just make sure the DAO is scalable is accommodate different databases.

2023-06-09 13:46 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ProfessorDAO.java
> +
a blank line is not needed here

2023-06-09 14:37 UTC, lucasz-student commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ProfessorDAO.java
> +
Thanks Jisha ! I've reviewed the suggestions and I'm making changes now. I will remove the blank lines, move the model and dao classes to the same package, make a service package, and use connection pool instead.

2023-06-13 13:24 UTC, adelagega commented
Accessing ResultSet: In your getGymById method, you're accessing the fields of the ResultSet directly after executing the query. The ResultSet initially points before the first record, so you need to call GymFields.next() before accessing the fields. 
I think you need to fix this method in all you dao classes. Also, I agree with Jisha's suggestions.

2023-06-13 14:30 UTC, VbKoshak approved these changes

2023-06-17 12:57 UTC, jishaGithub requested changes

2023-06-17 12:57 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ProfessorDAO.java
> +		try (Connection connection = (Connection) ConnectionManager.getSQLConnection().get();) {
You are creating connection in each DAO class , can you find an alternate approach to avoid such code duplication?

2023-06-17 13:21 UTC, jishaGithub requested changes

2023-06-17 13:21 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ConnectionManager.java
> +			Connection connection = DriverManager.getConnection(props.getProperty("db.url"), props.getProperty("db.user"), props.getProperty("db.password"));
check the indentations in the try{}

2023-06-17 13:21 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/GymDAO.java
> +
Remove extra line

2023-06-17 13:21 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ICreatableMultiRelationship.java
> +	public void create(A a, B b, C c);
in an interface, all methods and fields are implicitly public and abstract. You don't have to explicitly include it.

2023-06-17 13:21 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/IDAO.java
> +	public void delete(T t);
in an interface, all methods and fields are implicitly public and abstract. You don't have to explicitly include it.

2023-06-17 13:21 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ProfessorDAO.java
> +
```suggestion
import java.util.List;
import java.util.concurrent.ExecutionException;
import com.laba.solvd.database.Model.Professor;
import com.laba.solvd.database.Model.ResearchLab;
```

2023-06-17 13:21 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ResearchLabDAO.java
> +
```suggestion
	ps.executeUpdate();
		} catch (SQLException | InterruptedException | ExecutionException e) {
		       e.printStackTrace();
		}
```

2023-06-17 13:31 UTC, jishaGithub requested changes

2023-06-17 13:31 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/StudentDAO.java
> +			ResultSet StudentFields = psStudentFields.executeQuery();
Just like Adela mentioned earlier, you need to include StudentFields.next() to make the cursor point to the first row. I was getting an error without adding that. I am not sure how its working for you.

2023-06-17 13:31 UTC, jishaGithub commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ConnectionManager.java
> +		try (InputStream input = new FileInputStream("src/main/resources/db.properties")) {
I couldn't find this folder src/main/resources/db.properties

2023-06-19 02:21 UTC, adelagega commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/GymDAO.java
>  		try (Connection connection = (Connection) ConnectionManager.getSQLConnection().get();) {
Consider using an AbstractDao class as it simplifies the process of getting database connections and preparing SQL statements, which are common tasks for any DAO. Any class that extends AbstractDao can use these methods, helping to reduce code duplication.

2023-06-19 02:21 UTC, adelagega commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/IDAO.java
> +	public static final String GET_BY_ID = "SELECT * FROM %s WHERE id=?";
Do you think is a good idea to have these query statements as part of your interface? I believe that keeping the queries next to the code that uses them can make the code easier to understand than having them in this interface

2023-06-19 02:21 UTC, adelagega commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/GymDAO.java
>  			PreparedStatement UpdateGym = connection.prepareStatement("UPDATE gym set Location=?, set gymAge=?, set price=? WHERE id=?");
You should not use SET keyword before every column you want to update. Use commas to separate each column.

2023-06-19 02:21 UTC, adelagega commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/GymDAO.java
> -
After the executeQuery() function is called, a ResultSet is returned, which is a cursor pointing to its current row of data. Initially, this cursor is positioned before the first row. To move the cursor, we use next() method in an if statement

2023-06-19 02:21 UTC, adelagega commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/database/DAO/ConnectionManager.java
> +}
I'm commenting here because there's the only line where the plus sign is visible :
1.You have a custom, inner class Connection : Maybe you should consider changing the name of this class because In java.sql, Connection is an interface that provides methods for interacting with a database and it creates confusion.
2.The method public static Future getSQLConnection() - does not specify the type of 'Future' it returns. 
3. In the method private Connection fetchOrStartConnection() - if the pool is full and none of the connections are idle, this method will loop forever. 
4. You a creating an executor service but you are not shutting it down anywhere. 
5. The method StartReturnableThread(Callable callable) it doesn't actually start a new thread every time it's called. It just submits a new task to the executor service.

2023-06-19 02:23 UTC, adelagega commented
I have commented 5 days ago, but I just noticed my comments have been pending. Please ignore comments related to changes you have already made.

2023-06-22 02:39 UTC, jishaGithub approved these changes

2023-06-27 02:00 UTC, merged

2023-06-27 09:22 UTC, VbKoshak commented on JDBC/DatabasesPractice/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.unusedLocal=preserve
It should not be a part of PR

2023-06-27 09:22 UTC, VbKoshak commented on JDBC/DatabasesPractice/src/main/java/com/laba/solvd/Main.java
> +		Arrays.asList(gs.getAllGyms()).forEach((p) -> p.forEach((s) -> System.out.println(s.getLocation())));}
This is the reason we have service layer.
`GymService.printAllLocations()`